# Datasource
spring.datasource:
  url: jdbc:h2:./distances.h2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  driverClassName: org.h2.Driver
  username: sa
  password: password

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: update

# H2
spring.h2.console:
  enabled: true
  path: /h2

# Port
server.port: 16789

# Job
jobs.collect.morning.cron: "0 */15 7-10 * * MON-FRI"
jobs.collect.afternoon.cron: "0 */15 16-19 * * MON-FRI"

# Google API
google.api.key: ${API_KEY}
